name: unruff
channels:
  - defaults
dependencies:
  - anyio=4.10.0=py311haa95532_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py311h02ab6af_0
  - asttokens=3.0.0=py311haa95532_0
  - async-lru=2.0.5=py311haa95532_0
  - attrs=25.4.0=py311haa95532_2
  - babel=2.16.0=py311haa95532_0
  - beautifulsoup4=4.13.5=py311haa95532_0
  - bleach=6.2.0=py311haa95532_0
  - brotlicffi=1.1.0.0=py311h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - certifi=2025.11.12=py311haa95532_0
  - cffi=2.0.0=py311h02ab6af_1
  - charset-normalizer=3.4.4=py311haa95532_0
  - colorama=0.4.6=py311haa95532_0
  - comm=0.2.3=py311haa95532_0
  - debugpy=1.8.16=py311h885b0b7_1
  - decorator=5.2.1=py311haa95532_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=2.2.1=py311haa95532_0
  - h11=0.16.0=py311haa95532_1
  - httpcore=1.0.9=py311haa95532_0
  - httpx=0.28.1=py311haa95532_1
  - idna=3.11=py311haa95532_0
  - ipykernel=6.31.0=py311h4442805_0
  - ipython=9.7.0=py311haa95532_0
  - ipython_pygments_lexers=1.1.1=py311haa95532_0
  - ipywidgets=8.1.7=py311haa95532_0
  - jedi=0.19.2=py311haa95532_0
  - jinja2=3.1.6=py311haa95532_0
  - json5=0.9.25=py311haa95532_0
  - jsonschema=4.25.0=py311haa95532_1
  - jsonschema-specifications=2025.9.1=py311haa95532_0
  - jupyter=1.1.1=py311haa95532_0
  - jupyter-lsp=2.2.5=py311haa95532_0
  - jupyter_client=8.6.3=py311haa95532_1
  - jupyter_console=6.6.3=py311haa95532_0
  - jupyter_core=5.8.1=py311haa95532_0
  - jupyter_events=0.12.0=py311haa95532_0
  - jupyter_server=2.16.0=py311haa95532_0
  - jupyter_server_terminals=0.5.3=py311haa95532_0
  - jupyterlab=4.4.7=py311haa95532_0
  - jupyterlab_pygments=0.3.0=py311haa95532_0
  - jupyterlab_server=2.28.0=py311haa95532_0
  - jupyterlab_widgets=3.0.15=py311haa95532_0
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.20=h83e8143_0
  - libzlib=1.3.1=h02ab6af_0
  - markupsafe=3.0.2=py311h827c3e9_0
  - matplotlib-inline=0.2.1=py311haa95532_0
  - mistune=3.1.2=py311haa95532_0
  - nbclient=0.10.2=py311haa95532_0
  - nbconvert=7.16.6=py311haa95532_0
  - nbconvert-core=7.16.6=py311haa95532_0
  - nbconvert-pandoc=7.16.6=py311haa95532_0
  - nbformat=5.10.4=py311haa95532_0
  - nest-asyncio=1.6.0=py311haa95532_0
  - notebook=7.4.5=py311haa95532_0
  - notebook-shim=0.2.4=py311haa95532_0
  - openssl=3.0.18=h543e019_0
  - overrides=7.7.0=py311haa95532_0
  - packaging=25.0=py311haa95532_1
  - pandoc=3.8=haa95532_0
  - pandocfilters=1.5.1=py311haa95532_0
  - parso=0.8.5=py311haa95532_0
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.0=py311haa95532_0
  - prometheus_client=0.21.1=py311haa95532_0
  - prompt-toolkit=3.0.52=py311haa95532_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py311h02ab6af_1
  - pure_eval=0.2.3=py311haa95532_0
  - pycparser=2.23=py311haa95532_0
  - pygments=2.19.2=py311haa95532_0
  - pysocks=1.7.1=py311haa95532_1
  - python=3.11.10=h4607a30_0
  - python-dateutil=2.9.0post0=py311haa95532_2
  - python-fastjsonschema=2.20.0=py311haa95532_0
  - python-json-logger=3.2.1=py311haa95532_0
  - pywin32=311=py311h885b0b7_0
  - pywinpty=2.0.15=py311h72d21ff_0
  - pyyaml=6.0.3=py311hb9a58be_0
  - pyzmq=27.1.0=py311h7149c55_1
  - qtconsole=5.7.0=py311haa95532_0
  - qtpy=2.4.3=py311haa95532_0
  - referencing=0.37.0=py311haa95532_0
  - requests=2.32.5=py311haa95532_1
  - rfc3339-validator=0.1.4=py311haa95532_0
  - rfc3986-validator=0.1.1=py311haa95532_0
  - rpds-py=0.28.0=py311h114bc41_0
  - send2trash=1.8.2=py311haa95532_1
  - setuptools=80.9.0=py311haa95532_0
  - six=1.17.0=py311haa95532_0
  - sniffio=1.3.0=py311haa95532_0
  - soupsieve=2.5=py311haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=py311haa95532_0
  - terminado=0.18.1=py311haa95532_0
  - tinycss2=1.4.0=py311haa95532_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.1=py311h827c3e9_0
  - traitlets=5.14.3=py311haa95532_0
  - typing-extensions=4.15.0=py311haa95532_0
  - typing_extensions=4.15.0=py311haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py311haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=py311haa95532_0
  - webencodings=0.5.1=py311haa95532_1
  - websocket-client=1.8.0=py311haa95532_0
  - wheel=0.45.1=py311haa95532_0
  - widgetsnbextension=4.0.14=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_1
  - winpty=0.4.3=4
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
    - a2wsgi==1.10.10
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.13.2
    - aiohttp-asgi-connector==1.1.2
    - aiohttp-retry==2.9.1
    - aiosignal==1.4.0
    - aiosqlite==0.21.0
    - alembic==1.17.2
    - amqp==5.3.1
    - annotated-doc==0.0.4
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - appdirs==1.4.4
    - argcomplete==3.6.3
    - arrow==1.4.0
    - asgiref==3.11.0
    - asyncssh==2.21.1
    - atpublic==6.0.2
    - bentoml==1.4.30
    - billiard==4.2.3
    - binaryornot==0.4.4
    - blinker==1.9.0
    - cachetools==6.2.2
    - catboost==1.2.8
    - category-encoders==2.9.0
    - cattrs==23.1.2
    - celery==5.5.3
    - chardet==5.2.0
    - click==8.3.1
    - click-didyoumean==0.3.1
    - click-option-group==0.5.9
    - click-plugins==1.1.1.2
    - click-repl==0.3.0
    - cloudpickle==3.1.2
    - comet-ml==3.54.2
    - configobj==5.0.9
    - contourpy==1.3.3
    - cookiecutter==2.6.0
    - cryptography==46.0.3
    - cycler==0.12.1
    - databricks-sdk==0.73.0
    - dictdiffer==0.9.0
    - diskcache==5.6.3
    - distro==1.9.0
    - docker==7.1.0
    - dpath==2.2.0
    - dulwich==0.24.10
    - dvc==3.64.0
    - dvc-data==3.16.12
    - dvc-http==2.32.0
    - dvc-objects==5.1.2
    - dvc-render==1.0.2
    - dvc-studio-client==0.22.0
    - dvc-task==0.40.2
    - entrypoints==0.4
    - everett==3.1.0
    - fastapi==0.122.0
    - feature-engine==1.9.3
    - filelock==3.20.0
    - flask==3.1.2
    - flask-cors==6.0.1
    - flatten-dict==0.4.2
    - flufl-lock==8.2.0
    - fonttools==4.60.1
    - fqdn==1.5.1
    - frozenlist==1.8.0
    - fsspec==2025.10.0
    - funcy==2.0
    - gitdb==4.0.12
    - gitpython==3.1.45
    - google-auth==2.43.0
    - grandalf==0.8
    - graphene==3.4.3
    - graphql-core==3.2.7
    - graphql-relay==3.2.0
    - greenlet==3.2.4
    - gto==1.9.0
    - httpx-ws==0.8.2
    - huey==2.5.4
    - hydra-core==1.3.2
    - importlib-metadata==8.7.0
    - isoduration==20.11.0
    - iterative-telemetry==0.0.10
    - itsdangerous==2.2.0
    - joblib==1.5.2
    - jsonpointer==3.0.0
    - kantoku==0.18.3
    - kiwisolver==1.4.9
    - kombu==5.5.4
    - lark==1.3.1
    - lightgbm==4.6.0
    - mako==1.3.10
    - markdown-it-py==4.0.0
    - matplotlib==3.10.7
    - mdurl==0.1.2
    - mlflow==3.6.0
    - mlflow-skinny==3.6.0
    - mlflow-tracing==3.6.0
    - multidict==6.7.0
    - narwhals==2.12.0
    - networkx==3.6
    - numpy==2.3.5
    - nvidia-ml-py==13.580.82
    - omegaconf==2.3.0
    - opentelemetry-api==1.38.0
    - opentelemetry-instrumentation==0.59b0
    - opentelemetry-instrumentation-aiohttp-client==0.59b0
    - opentelemetry-instrumentation-asgi==0.59b0
    - opentelemetry-proto==1.38.0
    - opentelemetry-sdk==1.38.0
    - opentelemetry-semantic-conventions==0.59b0
    - opentelemetry-util-http==0.59b0
    - orjson==3.11.4
    - pandas==2.3.3
    - pathspec==0.12.1
    - patsy==1.0.2
    - pillow==12.0.0
    - pip-requirements-parser==32.0.1
    - pipx==1.8.0
    - plotly==6.5.0
    - propcache==0.4.1
    - protobuf==6.33.1
    - pyarrow==22.0.0
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.2
    - pydantic==2.12.5
    - pydantic-core==2.41.5
    - pydantic-settings==2.12.0
    - pydot==4.0.1
    - pygit2==1.19.0
    - pygtrie==2.5.0
    - pyparsing==3.2.5
    - python-box==6.1.0
    - python-dotenv==1.2.1
    - python-graphviz==0.21
    - python-multipart==0.0.20
    - python-slugify==8.0.4
    - pytz==2025.2
    - requests-toolbelt==1.0.0
    - rfc3987-syntax==1.1.0
    - rich==14.2.0
    - rich-toolkit==0.17.0
    - rsa==4.9.1
    - ruamel-yaml==0.18.16
    - ruamel-yaml-clib==0.2.15
    - schema==0.7.8
    - scikit-learn==1.7.2
    - scipy==1.16.3
    - scmrepo==3.5.6
    - seaborn==0.13.2
    - semantic-version==2.10.0
    - semver==3.0.4
    - sentry-sdk==2.46.0
    - shellingham==1.5.4
    - shortuuid==1.0.13
    - shtab==1.8.0
    - simple-di==0.1.5
    - simplejson==3.20.2
    - smmap==5.0.2
    - sqlalchemy==2.0.44
    - sqlparse==0.5.3
    - sqltrie==0.11.2
    - starlette==0.50.0
    - statsmodels==0.14.5
    - tabulate==0.9.0
    - text-unidecode==1.3
    - threadpoolctl==3.6.0
    - tomli-w==1.2.0
    - tomlkit==0.13.3
    - tqdm==4.67.1
    - typer==0.20.0
    - typing-inspection==0.4.2
    - tzdata==2025.2
    - uri-template==1.3.0
    - userpath==1.9.2
    - uvicorn==0.38.0
    - vine==5.1.0
    - voluptuous==0.15.2
    - waitress==3.0.2
    - wandb==0.23.0
    - watchfiles==1.1.1
    - webcolors==25.10.0
    - werkzeug==3.1.3
    - wrapt==1.17.3
    - wsproto==1.3.2
    - wurlitzer==3.1.1
    - xgboost==3.1.2
    - yarl==1.22.0
    - yellowbrick==1.5
    - zc-lockfile==4.0
    - zipp==3.23.0
prefix: C:\Users\natar\anaconda3\envs\unruff
